
services:
  backend:
    build: .
    container_name: goldenia-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP
      - FLASK_ENV
      - DATABASE_URL
      - SECRET_KEY
      - SQLALCHEMY_TRACK_MODIFICATIONS
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    platform: linux/amd64 
    container_name: goldenia-db
    environment:
      POSTGRES_DB: goldenia_wallet
      POSTGRES_USER: goldenia_user
      POSTGRES_PASSWORD: goldenia
    ports:
      - "5432:5432"
