"""Add currency column to transaction table

Revision ID: 07e1cc1955b4
Revises: 0c3b015546ce
Create Date: 2025-04-15 15:56:23.943755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e1cc1955b4'
down_revision = '0c3b015546ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
