"""Add currency_from and currency_to to Transaction

Revision ID: 6cb88efa175b
Revises: e5e1954035d7
Create Date: 2025-04-15 20:12:37.021487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb88efa175b'
down_revision = 'e5e1954035d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_from', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('currency_to', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('currency_to')
        batch_op.drop_column('currency_from')

    # ### end Alembic commands ###
