"""Add currency_from and currency_to to Transaction

Revision ID: 7a9dce39dfef
Revises: 6cb88efa175b
Create Date: 2025-04-15 20:17:19.199346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9dce39dfef'
down_revision = '6cb88efa175b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('converted_amount')

    # ### end Alembic commands ###
